// Сниппеты доки к примеру DumbModal.
//
// Отдельный файл, потому что подсветка считается НА СБОРКЕ: плагин
// playground/snippets.ts выполняет этот модуль в Node, гонит каждую строку
// через Shiki и подменяет экспорт на { code, html }. Отсюда два требования: в
// файле только строки и ни одного импорта.
export default {
  install: 'pnpm add @solid-dumb-kit/modal',

  basic: [
    "import { createSignal } from 'solid-js'",
    "import { DumbModal } from '@solid-dumb-kit/modal'",
    '',
    'export default function Booking() {',
    '  const [open, setOpen] = createSignal(false)',
    '',
    '  return (',
    '    <>',
    '      <button class="btn" onClick={() => setOpen(true)}>',
    '        Открыть',
    '      </button>',
    '',
    '      <DumbModal',
    '        open={open}',
    '        onClose={() => setOpen(false)}',
    '        title={<b>Бронь №1042</b>}',
    '        footer={',
    '          <div class="flex justify-end gap-2">',
    '            <button class="btn btn-sm" onClick={() => setOpen(false)}>',
    '              Отмена',
    '            </button>',
    '            <button class="btn btn-sm btn-neutral" onClick={save}>',
    '              Сохранить',
    '            </button>',
    '          </div>',
    '        }',
    '      >',
    '        <p>Двухместный, с 14 по 21 июня.</p>',
    '      </DumbModal>',
    '    </>',
    '  )',
    '}',
  ].join('\n'),

  guard: [
    '// Esc и клик по подложке закрывают окно молча — вместе с несохранённой',
    '// правкой. onBeforeClose даёт это оспорить: вернули false — окно осталось.',
    '// Спрашиваем ОКНОМ: работа встала, и вопрос про то самое окно, что на',
    '// экране, — плашке в углу тут не место.',
    'const guard = () => {',
    '  if (!dirty()) return true',
    "  return modal.confirm('Правка не сохранена. Закрыть окно?', {",
    "    title: 'Есть несохранённое',",
    "    yes: 'Закрыть без сохранения',",
    "    no: 'Остаться',",
    '    danger: true,',
    '  })',
    '}',
    '',
    '<DumbModal open={open} onClose={() => setOpen(false)} onBeforeClose={guard}>',
    '  …',
    '</DumbModal>',
  ].join('\n'),

  host: [
    "import { DumbModalHost, modal } from '@solid-dumb-kit/modal'",
    '',
    '// ОДИН раз на приложение, рядом с корнем: он рисует то, что пришло в шину',
    'export default function App() {',
    '  return (',
    '    <>',
    '      <Router />',
    '      <DumbModalHost />',
    '    </>',
    '  )',
    '}',
    '',
    '// дальше вопрос задаётся откуда угодно — в том числе из кода, который',
    '// про разметку ничего не знает',
    "const ok = await modal.confirm('Удалить бронь безвозвратно?', {",
    "  title: 'Удаление',",
    "  yes: 'Удалить',",
    "  no: 'Отмена',",
    '  danger: true,',
    '})',
    'if (ok) await api.remove(id)',
  ].join('\n'),

  ask: [
    '// несколько ответов вместо «да/нет». Возвращается value нажатой кнопки;',
    '// закрыли не ответив — то, что указано в dismiss.',
    "const what = await modal.ask('Файл изменён и на диске, и здесь.', [",
    "  { label: 'Перечитать с диска', value: 'reload', kind: 'primary' },",
    "  { label: 'Оставить моё', value: 'keep' },",
    "  { label: 'Сохранить копию', value: 'copy' },",
    "], { title: 'Расхождение', dismiss: 'keep' })",
    '',
    '// вопрос без безопасного умолчания закрывать нельзя: ответ придётся нажать',
    "await modal.confirm('Стереть все данные устройства?', { dismissible: false })",
    '',
    '// сообщение с одной кнопкой — замена alert(), не вешающая вкладку',
    "await modal.alert('Отчёт готов и отправлен на почту.')",
  ].join('\n'),

  layer: [
    '// Окно рисуется нативным <dialog>, то есть в top layer. Отсюда три вещи',
    '// даром: ловушка фокуса, Esc и запрет прокрутки за окном.',
    '//',
    '// И отсюда же порядок без z-index: вложенное окно ложится выше родителя',
    '// просто потому, что открыто позже, а тост — выше обоих.',
    '<DumbModal open={outer} onClose={closeOuter} title={<b>Первое</b>}>',
    '  <button class="btn btn-sm" onClick={() => setInner(true)}>',
    '    Открыть поверх',
    '  </button>',
    '',
    '  <DumbModal open={inner} onClose={closeInner} width="min(380px, 92vw)">',
    '    <p>Esc закроет сначала это окно, потом первое.</p>',
    '  </DumbModal>',
    '</DumbModal>',
  ].join('\n'),
}

/** язык там, где это не tsx */
export const langs = { install: 'sh' }
